name: Build website

on:
  workflow_dispatch:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install rust
      run: |
        rustup install stable
        rustup default stable
    - name: Run tests
      run: |
        cd simulator
        cargo test --verbose
        cd ..
    - name: setup wasm-pack
      uses: jetli/wasm-pack-action@v0.4.0
    - name: Build Wasm
      run: |
        cd simulator
        wasm-pack build --release
        cd ..
    - name: setup-node
      uses: actions/setup-node@v4
      with: 
        node-version: 18
    - name: build webpage
      run: |
        cd web
        npm install
        npm run build-only
        cd ..
    - name: upload pages artifact
      uses: actions/upload-pages-artifact@v3
      with: 
        name: build_artifact
        path: web/dist/

    # Deployment job
  deploy:
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Configure Pages
        uses: actions/configure-pages@v4
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

    
